language: go
go:
  - 1.9.1
before_install:
  - go get -v github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
install:
  - glide install
script:
  - make
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN