language: go
go:
  - 1.9.1
go_import_path: github.com/kostkobv/messagebirdtest
before_install:
  - go get -v github.com/Masterminds/glide
  - go get -u gopkg.in/alecthomas/gometalinter.v1
install:
  - glide install
  - gometalinter.v1 -i
script:
  - bash run_tests.sh
  - make lint
after_success:
  - bash <(curl -s https://codecov.io/bash)