language: go
go:
  - 1.9.1
before_install:
  - go get -v github.com/Masterminds/glide
  - go get -u github.com/mattn/goveralls
  - go get -u gopkg.in/alecthomas/gometalinter.v1
install:
  - glide install
script:
  - make
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN